# Generated by Django 4.1.2 on 2022-10-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('ssn', models.CharField(max_length=9, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
