# Generated by Django 4.1.2 on 2022-10-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ssn',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
